import { Course } from "@/components/courses/types";

export const courses: Course[] = [
  {
    id: "1",
    title: "Blockchain Research",
    category: "web3",
    categoryLabel: "Web3 & blockchain",
    description:
      "Explore the fundamentals of blockchain technology, emerging trends, and real-world applications. Develop the research skills needed to analyze blockchain ecosystems, evaluate innovations, and uncover insights shaping the future of decentralized technology.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "100000",
    available: true,
    discounted: true,
  },
  {
    id: "2",
    title: "Frontend Software Development",
    category: "dev-design",
    categoryLabel: "Development & design",
    description:
      "Learn to build interactive products with popular front-end tools. Gain practical skills through hands-on projects and turn your ideas into engaging web experiences.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "150000",
    available: true,
  },
  {
    id: "3",
    title: "Backend Software Development",
    category: "dev-design",
    categoryLabel: "Development & design",
    description:
      "Learn how to build the server-side of modern web applications, including APIs, databases, authentication, business logic, and secure data management.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "150000",
    available: true,
  },
  {
    id: "4",
    title: "Blockchain Development",
    category: "web3",
    categoryLabel: "Web3 & blockchain",
    description:
      "Write, test, and deploy your own smart contracts on Ethereum and BSC, then ship a working dApp from scratch.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "170000",
    available: false,
  },
  {
    id: "5",
    title: "UI/UX Design",
    category: "dev-design",
    categoryLabel: "Development & design",
    description:
      "Design products people enjoy using. Learn research, wireframing, and prototyping through real client-style briefs.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "150000",
    available: false,
  },
  {
    id: "6",
    title: "Graphics Design",
    category: "dev-design",
    categoryLabel: "Development & design",
    description:
      "Learn how to create stunning visuals that communicate ideas effectively. Develop practical skills in design principles, branding, typography, color, and industry-standard tools through hands-on projects.",
    duration: "12 weeks",
    format: "Online & physical",
    price: "50000",
    available: true,
  },
  {
    id: "7",
    title: "Data Analysis",
    category: "data-security",
    categoryLabel: "Data & security",
    description:
      "Learn how to turn raw data into meaningful insights using essential data analysis tools and techniques. Build practical skills in data cleaning, visualization, interpretation, and reporting to make smarter, data-driven decisions.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "100000",
    available: true,
    discounted: true,
  },
  {
    id: "8",
    title: "Cybersecurity",
    category: "data-security",
    categoryLabel: "Data & security",
    description:
      "Learn to identify, prevent, and respond to digital threats, and build the fundamentals for a career protecting systems.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "100000",
    available: true,
    discounted: true,
  },
  {
    id: "9",
    title: "Cryptocurrency Fundamental/Trading",
    category: "trading",
    categoryLabel: "Trading & finance",
    description:
      "Learn the fundamentals of cryptocurrency trading, from market analysis and risk management to trading strategies and portfolio planning. Develop the knowledge and discipline needed to navigate crypto markets with greater confidence.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "72000",
    available: true,
    discounted: true,
  },
  {
    id: "10",
    title: "Forex Trading",
    category: "trading",
    categoryLabel: "Trading & finance",
    description:
      "Learn to read currency markets, manage risk, and build a trading plan you can actually stick to.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "72000",
    available: true,
    discounted: true,
  },
  {
    id: "11",
    title: "Combo Course (Forex and Crypto)",
    category: "trading",
    categoryLabel: "Trading & finance",
    description:
      "Learn the fundamentals of Forex and cryptocurrency trading, from market analysis and trading strategies to risk management and portfolio management.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "130000",
    available: true,
  },
  {
    id: "12",
    title: "Coding for Kids",
    category: "dev-design",
    categoryLabel: "Development & design",
    description:
      "A fun, beginner-friendly course that introduces kids to programming through interactive projects and games. Learn fundamental coding concepts and problem-solving skills while building exciting projects.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "30000",
    available: true,
  },
  {
    id: "13",
    title: "Social Media Marketing",
    category: "social-media",
    categoryLabel: "Social media",
    description:
      "Learn how to use social media to build a strong online presence, reach the right audience, create engaging content, and grow a brand. ",
    duration: "8 weeks",
    format: "Online & physical",
    price: "50000",
    available: true,
  },
  {
    id: "14",
    title: "Community Moderation/Management",
    category: "community",
    categoryLabel: "Community",
    description:
      "Learn how to build, manage, and grow online communities by engaging members, maintaining healthy discussions, handling conflicts, and enforcing community guidelines.",
    duration: "8 weeks",
    format: "Online & physical",
    price: "50000",
    available: true,
  },
];
